const nombreProductosElectronica = [
    { id: 1, nombre: "Camara Web", precio: 3200, img: "../imagen/camara.jpeg" },
    { id: 2, nombre: "Consola", precio: 4100, img: "../imagen/consola.jpeg" },
    { id: 3, nombre: "Auricular BLUETOOTH", precio: 1950, img: "../imagen/p47.jpeg" },
    { id: 4, nombre: "Webcam", precio: 2800, img: "../imagen/webcam2.jpg" },
    //{ id: 5, nombre: "Tv Box 4k", precio: 6670, img: "../imagen/tvbox.jpeg" },
    { id: 6, nombre: "Soporte De TV Fijo", precio: 870, img: "../imagen/soporteTv.jpeg" },
    //{ id: 7, nombre: "Drone Y20", precio: 9500, img: "../imagen/drone.jpg" },
    //{ id: 8, nombre: "Drone Cuadricóptero", precio: 9900, img: "../imagen/drone2.jpg" },
    { id: 9, nombre: "Joystick PS2", precio: 1150, img: "../imagen/joystick_ps2.jpeg" },
    //{ id: 10, nombre: "Joystick inalámbrico PS3", precio: 1500, img: "../imagen/joystick_ps3.jpeg" },
    { id: 11, nombre: "Laser Multipunto Audio Rítmico", precio: 3100, img: "../imagen/multipunto.jpg" },
    { id: 12, nombre: "Media Esfera Bluetooth", precio: 3600, img: "../imagen/media_bola.jpg" },
    { id: 13, nombre: "Proyector de Estrellas", precio: 1700, img: "../imagen/media_bola_estrella.jpeg" },
    { id: 14, nombre: "Reloj Proyector", precio: 1660, img: "../imagen/despertador_estrellas.jpg" },
    { id: 15, nombre: "Repetidor de Wifi", precio: 3500, img: "../imagen/repetidor_wifi.jpeg" },
    { id: 16, nombre: "Tablet 7″", precio: 10500, img: "../imagen/tablet.jpeg" },
    { id: 17, nombre: "Zapatilla Redonda", precio: 1700, img: "../imagen/zapatilla.jpg" },
]