const nombreProductosElectronica = [
    { id: 1, nombre: "Patillera Profesional", precio: 2940, img: "../imagen/patillera.jpeg" },
    { id: 2, nombre: "Afeitadora 3 en 1", precio: 3120, img: "../imagen/afeitadore3en1.jpeg" },
    { id: 3, nombre: "Secador de pelo NOVA", precio: 900, img: "../imagen/secador450.jpg" },
    { id: 4, nombre: "Torno para uñas profesional", precio: 2560, img: "../imagen/tornoChico.jpeg" },
    { id: 5, nombre: "Masajeador exfoliante 5 en 1", precio: 880, img: "../imagen/exfoliante.jpeg" },
    { id: 6, nombre: "Cabina de uñas SUN one 48w", precio: 3500, img: "../imagen/cabinaUñas48.jpeg" },
    { id: 7, nombre: "Cabina de uñas SUN 54w", precio: 5000, img: "../imagen/cabinaUñas54.jpeg" },
    { id: 8, nombre: "Cabina de uñas SUN 120W", precio: 6800, img: "../imagen/cabinaUñas120.jpeg" },
    { id: 9, nombre: "Cabina de uñas Panda 36w", precio: 1900, img: "../imagen/cabinaUñasPanda.jpeg" },
    { id: 10, nombre: "Máquina cortapelo para perros con accesorios", precio: 2900, img: "../imagen/corta_pelo_perro.jpg" },
    { id: 11, nombre: "Máquina corta pelo ORYX", precio: 1840, img: "../imagen/corta_pelo_orix.jpg" },
    { id: 12, nombre: "Máquina corta pelo VINTAGE", precio: 3100, img: "../imagen/patillera1.jpeg" },
    { id: 13, nombre: "Máquina corta pelo VINTAGE", precio: 4100, img: "../imagen/patillera2.jpeg" },
    { id: 14, nombre: "Plancha de pelo flequillera", precio: 580, img: "../imagen/planchita.jpeg" },
    { id: 15, nombre: "Secador de pelo NOVA", precio: 950, img: "../imagen/secador480.jpg" },
    { id: 16, nombre: "Secador de pelo NOVA", precio: 1000, img: "../imagen/secador520.jpg" },
    { id: 17, nombre: "Torno para uña MERCEDES 2000", precio: 4900, img: "../imagen/torno_profe.jpeg" },
    { id: 18, nombre: "Torno para uñas a pila", precio: 770, img: "../imagen/torno_pila.jpg" },
]