const nombreProductosElectronica = [
    { id: 1, nombre: "Guirnalda LED 9mt", precio: 800, img: "../imagen/guirnalda_9mt.jpeg" },
    { id: 2, nombre: "Guirnalda LED x50", precio: 600, img: "../imagen/guirnalda_50.jpeg" },
    { id: 3, nombre: "TRGB tira de LED rgb 5050", precio: 2900, img: "../imagen/tiraRGB.jpeg" },
    { id: 4, nombre: "Tira de LED 5050 – Luz fría ", precio: 2250, img: "../imagen/tiraledCalida.jpeg" },
    { id: 5, nombre: "Tira de LED 5050 – Luz cálida 20w", precio: 2250, img: "../imagen/tira-calida-.jpg" },
    { id: 6, nombre: "Manguera LED multicolor 10mts", precio: 3000, img: "../imagen/manguera10.jpeg" },
    { id: 7, nombre: "Manguera LED cálida 10mts", precio: 3000, img: "../imagen/manguera10_calida.jpeg" },
    { id: 8, nombre: "Manguera LED blanca 10mts", precio: 3000, img: "../imagen/manguera10_fira.jpeg" },
    { id: 9, nombre: "Guirnaldas bolas de hilo 5cm y 6cm", precio: 740, img: "../imagen/bolas_10cm.jpg" },
    { id: 10, nombre: "Cortina luces led", precio: 690, img: "../imagen/colgantes_letras.jpg" },
    { id: 11, nombre: "Estaca Solar x4", precio: 3850, img: "../imagen/estacax4.jpg" },
    { id: 12, nombre: "lampara Bluethoot con Parlante y Control", precio: 1520, img: "../imagen/lamparaBluethoot.jpg" },
    { id: 13, nombre: "Lámpara giratoria RGB", precio: 500, img: "../imagen/lampara_giratoria.jpeg" },
    { id: 14, nombre: "Lámpara giratoria Doble", precio: 950, img: "../imagen/lampra_giratoria_doble.jpeg" },
    { id: 15, nombre: "Lámpara LED 9wrecargable USB", precio: 1000, img: "../imagen/lamapra_recargable_9y12.jpg" },
    { id: 16, nombre: "Lámpara LED 12w recargable USB", precio: 1380, img: "../imagen/lamapra_recargable_9y12.jpg" },
    //{ id: 16, nombre: "Luz protón 18 LED", precio: 2800, img: "../imagen/proton.jpeg" },
    { id: 17, nombre: "Lámpara LED 10cm", precio: 800, img: "../imagen/lamapra_led_10cm.jpg" },
    { id: 18, nombre: "Lámpara RGB 5W", precio: 1000, img: "../imagen/lamparaBlue.jpeg" },
    { id: 19, nombre: "Luz de emergencia 30 LED", precio: 1380, img: "../imagen/eme30.jpg" },
    { id: 20, nombre: "Luz de emergencia 60 LED", precio: 2700, img: "../imagen/luz_emergencia_60.jpeg" },
    { id: 21, nombre: "Cartel LED Kiosco", precio: 2400, img: "../imagen/kiosco.jpeg" },
    { id: 22, nombre: "Aplique Solar 100LED", precio: 1450, img: "../imagen/aplique_solar_100led.jpeg" },
    { id: 23, nombre: "Aplique Solar Doble", precio: 1550, img: "../imagen/aplique_solar_doble.jpeg" },
    { id: 24, nombre: "Luces led lluvia ROSA", precio: 2100, img: "../imagen/lluvia_rosa.jpeg" },
    { id: 25, nombre: "Pizarra luminosa corazón", precio: 1300, img: "../imagen/pizarra_corazon.jpg" },
    { id: 26, nombre: "Pizarra luminosa led 30×20", precio: 1600, img: "../imagen/pizarra_encastre.jpg" },
    { id: 27, nombre: "Luz protón 36 LED", precio: 4100, img: "../imagen/proton_36.png" },
    { id: 28, nombre: "Luz protón 54 LED", precio: 5800, img: "../imagen/proton-54.jpg" },
    { id: 29, nombre: "Reflector LED 20w", precio: 3050, img: "../imagen/reflector_rgb.jpg" },
    { id: 30, nombre: "Cartel 1 Metro", precio: 18600, img: "../imagen/cartel1Metro.jpg" },

]