const nombreProductosElectronica = [
    { id: 1, nombre: "Ventilador Recargable", precio: 3300, img: "../imagen/ventilado_chico.jfif" },
    { id: 2, nombre: "Mini licuadora portátil", precio: 2800, img: "../imagen/licuadora.jpeg" },
    { id: 3, nombre: "Mopa balde trapeador", precio: 2400, img: "../imagen/mopa.jpeg" },
    { id: 4, nombre: "Termo ACERO 1L", precio: 2400, img: "../imagen/termo bala.jpeg" },
    { id: 5, nombre: "Balanza de Baño", precio: 2650, img: "../imagen/balanzaBaño.jpeg" },
    { id: 6, nombre: "Vaso calentador 12v", precio: 1200, img: "../imagen/vasoTermicoAuto.jpeg" },
    { id: 7, nombre: "Alambre LED 2 metros", precio: 280, img: "../imagen/alambre_pila.jpg" },
    //{ id: 8, nombre: "Balanza de cocina 10 kg", precio: 1000, img: "../imagen/balanza_cocina_10kg.jpeg" },
    { id: 9, nombre: "Balanza de cocina 1kg", precio: 1250, img: "../imagen/balanza_cocina_1kg.jpeg" },
    { id: 10, nombre: "Balanza de cocina con Plato", precio: 2400, img: "../imagen/balanza_cocina_plato.jpeg" },
    { id: 11, nombre: "Balanza de vidrio hasta 5Kg", precio: 2500, img: "../imagen/balanza_cocina_vidrio.jpeg" },
    { id: 12, nombre: "Batidora de mano", precio: 3450, img: "../imagen/batidora_manp.jpeg" },
    { id: 13, nombre: "Figura de Base Con Espejo", precio: 860, img: "../imagen/figura_base_espejo.jpg" },
    { id: 14, nombre: "Cartel luminoso madera", precio: 1550, img: "../imagen/family.jpg" },
    { id: 15, nombre: "Cartel LED madera Home", precio: 1780, img: "../imagen/home.jpg" },
    { id: 16, nombre: "Cartel Luminoso Paz", precio: 1100, img: "../imagen/paz.jfif" },
    { id: 17, nombre: "Cartel luminoso madera", precio: 1150, img: "../imagen/cartelMadera.jfif" },
    { id: 18, nombre: "Cartel Happy Birthday", precio: 780, img: "../imagen/cartel_happy.jfif" },
    { id: 19, nombre: "Sandwichera eléctrica antiadherente", precio: 3500, img: "../imagen/sandwichera.jpeg" },
    { id: 20, nombre: "Kit velas LED", precio: 1800, img: "../imagen/kit_velas_rgb.jpg" },
    { id: 21, nombre: "Velas LED", precio: 70, img: "../imagen/velas_derretidas.jpeg" },
    { id: 22, nombre: "Velas LED", precio: 70, img: "../imagen/vela.jpeg" },
    { id: 23, nombre: "Waflera eléctrica antiadherente", precio: 3900, img: "../imagen/waflera.jpeg" },
    { id: 24, nombre: "Anafe eléctrico", precio: 3680, img: "../imagen/anafe1.jpeg" },
    { id: 25, nombre: "Minipimer", precio: 4100, img: "../imagen/minipimer.jpeg" },
    { id: 26, nombre: "Licuadora 1.5L", precio: 6400, img: "../imagen/licuadora_grande.jpeg" },
    { id: 27, nombre: "Maquina de pastas", precio: 5000, img: "../imagen/maquina_pasta.jpeg" },


]